name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  postman-tests:
    name: Run Postman Tests and Deploy Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman and htmlextra reporter
        run: npm install -g newman newman-reporter-htmlextra

      - name: Run API Tests with Newman
        run: |
          newman run Restfull_Booker.postman_collection.json \
            -e Book_Environment.postman_environment.json \
            -r htmlextra --reporter-htmlextra-export report.html

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          destination_dir: report

