name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/upload-artifact@v2


      - name: Set up Node.js
        uses: actions/upload-artifact@v2
        with:
          node-version: '22'

      - name: Install Newman
        run: npm install -g newman newman-reporter-htmlextra

      - name: Run Postman Tests
        run: |
          newman run Restfull_Booker.postman_collection.json \
            -e Book_Environment.postman_environment.json \
            -r htmlextra --reporter-htmlextra-export report.html \
            --verbose

      - name: Upload Report Artifact
        uses: actions/upload-artifact@v3
        with:
          name: newman-report
          path: report.html
