name: Run Postman Tests and Deploy Report

on:
  push:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman and Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Newman collection
        run: |
          newman run Restfull_Booker.postman_collection.json \
            -e Book_Environment.postman_environment.json \
            -r htmlextra \
            --reporter-htmlextra-export report.html

      - name: Upload report artifact
        uses: actions/upload-artifact@v3
        with:
          name: newman-report
          path: report.html

  deploy-report:
    needs: run-tests
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download report artifact
        uses: actions/download-artifact@v3
        with:
          name: newman-report

      - name: Move report to docs folder
        run: |
          mkdir -p docs
          mv report.html docs/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
